[package]
name = "slide_maker"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = {version = "1.0.188", features = ["derive"]}
serde-xml-rs = "0.6.0"
quick-xml = "0.30.0"
serde_derive = "1.0.188"
minidom = "0.15.2"
